language: node_js
sudo: false
addons:
  apt:
    sources:
    - debian-sid
    packages:
    - shellcheck
install: npm install jsonlint -g
script:
  - jsonlint -q Preferences.sublime-settings
  - shellcheck .bash_profile
